name: soniq
version: 0.0.1
description: Multithreaded, futuristic HTTP benchmarking tool.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/soniq
environment:
  sdk: ">=1.19.0"
dependencies:
  args: ^0.13.4
  check_for_update: ^1.0.0
  cli_util: ^0.1.1
  console: ^2.2.4
  http: ^0.11.3
  kilobyte: ^0.1.0
  merge_map: ^1.0.0
  string_scanner: ^1.0.0
  term_glyph: ^1.0.0
  yaml: ^2.1.12
  yamlicious: ^0.0.5
dev_dependencies:
  angel_framework: ^1.0.0
  build_runner: ^0.3.0
executables:
  soniq: soniq